# Generated by Django 5.1.5 on 2026-07-31 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.FloatField(blank=True, help_text='Poids cible en kg', null=True)),
                ('daily_calories', models.PositiveIntegerField(default=2200)),
                ('daily_water', models.PositiveIntegerField(default=2500, help_text="Objectif d'eau en ml")),
                ('daily_activity_minutes', models.PositiveIntegerField(default=30)),
                ('daily_steps', models.PositiveIntegerField(default=10000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
