# Generated by Django 5.1.5 on 2026-07-31 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('walking', 'Marche'), ('running', 'Course'), ('cycling', 'Vélo'), ('swimming', 'Natation'), ('yoga', 'Yoga'), ('gym', 'Musculation')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('distance', models.FloatField(blank=True, help_text='Distance en kilomètres', null=True)),
                ('calories_burned', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
